version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  node: circleci/node@2.0.0

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

defaults: &defaults
  working_directory: ~/repo

  docker:
    - image: circleci/node:erbium

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install
          command: npm ci

      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint-commit-message:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint Commit Message
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  test:
    working_directory: ~/repo

    parameters:
      os:
        type: executor
      node-version:
        type: string

    executor: << parameters.os >>

    steps:
      - attach_workspace:
          at: ~/repo

      - node/install:
          node-version: << parameters.node-version >>

      - run:
          name: Test
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage
            NODE_ENV: 'test'

      - store_test_results:
          path: ./coverage

      - store_artifacts:
          path: ./coverage

      - codecov/upload:
          file: ./coverage/cobertura-coverage.xml

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Release
          command: npx semantic-release --dry-run

workflows:
  version: 2.1

  test-and-release:
    jobs:
      - install

      - lint-commit-message:
          requires:
            - install

      - test:
          matrix:
            parameters:
              os: [linux, macos]
              node-version: ["16.4.2", "12.22.3", "14.17.3"]

          requires:
            - install

      - build:
          requires:
            - install

      - approve:
          type: approval
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
                - alpha
                - beta
                - next
                - 'pre/rc'

      - release:
          requires:
            - approve
          filters:
            branches:
              only:
                - master
                - alpha
                - beta
                - next
                - 'pre/rc'
