name: Release
on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next
jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup NodeJS 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Install Dependecies
        run: npm install

      - name: Lint Commit Message
        run: echo $(git log -1 --pretty=format:"%s") | npx commitlint

      - name: Lint Source
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:cov

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
          name: codecov-umbrella

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
