name: PR Inspection
on: [pull_request]

jobs:
  build-and-test:
    name: Build and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: false
          files: ./coverage/cobertura-coverage.xml
          name: codecov-umbrella

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Commit Message
        run: |
          npm i -D @commitlint/config-conventional
          echo $(git log -1 --pretty=format:"%s") | npx commitlint

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
