name: PR Inspection
on: [pull_request]

jobs:
  build-and-test:
    name: Build and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}

      - name: Get NPM Cache Directory Path
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Lint Commit Message
        run: |
          npm i -D @commitlint/config-conventional
          echo $(git log -1 --pretty=format:"%s") | npx commitlint

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM CI
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: false
          files: ./coverage/cobertura-coverage.xml
          name: codecov-umbrella
          verbose: false
