name: Release
on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next
jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get NPM Cache Directory Path
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: NPM CI
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup NodeJS 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Lint Commit Message
        run: echo $(git log -1 --pretty=format:"%s") | npx commitlint

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:cov

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
          name: codecov-umbrella

      - name: Release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
