name: Release
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Commit Message
        run: |
          npm i -D @commitlint/config-conventional
          echo $(git log -1 --pretty=format:"%s") | npx commitlint

      - name: Setup NodeJS 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
