#name: Release
#on:
#  push:
#    branches:
#      - master
#jobs:
#  main:
#    name: Release
#    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, 'skip ci')"
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Lint Commit Message
#        run: |
#          npm i -D @commitlint/config-conventional
#          echo $(git log -1 --pretty=format:"%s") | npx commitlint
#
#      - name: Create .npmrc
#        run: |
#          cat << EOF > "$HOME/.npmrc"
#            @naturalint:registry=https://registry.npmjs.org/
#            //registry.npmjs.org/:_authToken=$NPM_TOKEN
#            FirstName LastName (idan.ptichi@naturalint.com, idan.ptichi@naturalint.com)=true
#            email=reader@naturalint.com
#            always-auth=true
#            package-lock=false
#          EOF
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#
#      - name: Setup Node.js 12.x
#        uses: actions/setup-node@master
#        with:
#          node-version: 12.x
#
#      - name: Install Dependencies
#        run: npm install
#
#      - name: Bootstrap Packages
#        run: npm run bootstrap:no-ci
#
#      - name: Build
#        run: npm run build
#
#      - name: Test
#        run: npm run test
#
#      - name: Release
#        id: changesets
#        uses: changesets/action@master
#        with:
#          publish: npm run release
#          commit: "chore: version packages"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
